### ISSUE TITLE
✨ [Feature] 초기 프로젝트 세팅

### ISSUE THREAD

**Issue by jis-kim** [jis-kim/my-reading-journal#1]
### 요구 버전 
1. Node.js 18.18.x
2. NestJS 9.5.x
3. TypeScript 5.1.x
4. PostgreSQL 15.7.x 
5. Prisma 5.18.x
6. KAKAO OAuth2
7. Naver 책검색 API
8. Git을 사용한 버전 관리

## Todo
- [x] version 준수한 nest setting
- [x] eslint 설정 및 commit에 git hook 걸기
- [x] issue, pr template
